controller, dto, mappers, etc
OleksiiZaloznyi/bookstore pull request #2
Opened 2023-10-11 23:08 UTC by OleksiiZaloznyi

2023-10-12 10:51 UTC, kozhukhovsky approved these changes

2023-10-12 10:51 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/controller/BookController.java
> +
```suggestion
```

2023-10-15 09:14 UTC, Ivan95kos approved these changes
Great job

2023-10-15 16:38 UTC, Ivan95kos requested changes
Good job overall!

2023-10-15 16:38 UTC, Ivan95kos commented on src/main/java/com/example/bookstore/model/Book.java
> +//@RequiredArgsConstructor
uncomment this line

2023-10-15 16:38 UTC, Ivan95kos commented on src/main/java/com/example/bookstore/model/Book.java
> +    @NotNull
It is better to use the `@Column(nullable = false)` for Entity

2023-10-16 11:01 UTC, okuzan approved these changes

2023-10-24 09:24 UTC, merged