Spring Boot JWT completed
OleksiiZaloznyi/bookstore pull request #5
Opened 2024-01-23 13:19 UTC by OleksiiZaloznyi

2024-01-23 17:00 UTC, okuzan requested changes

2024-01-23 17:00 UTC, okuzan commented on src/main/java/com/example/bookstore/config/SecurityConfig.java
> +                .addFilterBefore(jwtAuthenticationFilter, UsernamePasswordAuthenticationFilter.class)
let's add these to permitted
`          .requestMatchers("/auth/**", "/swagger-ui/**", "/v3/api-docs/**")`

2024-01-24 11:11 UTC, okuzan approved these changes

2024-01-24 11:11 UTC, okuzan commented on src/test/resources/application.properties
> +jwt.secret=hellomates1234567890asdfghjklwertyuisdsdsdsdsd
```suggestion
jwt.secret=hellomates1234567890asdfghjklwertyuisdsdsdsdsd

```
always have one empty line at the EOF

2024-01-24 21:58 UTC, merged

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/dto/category/CategoryRequestDto.java
> +//package com.example.bookstore.dto.category;
?

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/dto/category/CategoryResponseDto.java
> +//package com.example.bookstore.dto.category;
?

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/dto/book/BookDtoWithoutCategoryIds.java
> +
empty line

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/controller/CategoryController.java
> +
empty line

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/mapper/CategoryMapper.java
> +
empty line

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/service/CategoryService.java
> +
empty line

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/java/com/example/bookstore/service/CategoryServiceImpl.java
> +
empty line

2024-01-25 12:04 UTC, kozhukhovsky commented on src/main/resources/db/changelog/changes/13-add-book-to-category.yaml
> +#databaseChangeLog:
?

2024-01-25 14:32 UTC, OleksiiZaloznyi commented on src/main/resources/db/changelog/changes/13-add-book-to-category.yaml
> +#databaseChangeLog:
forgot to delete this

2024-01-25 14:32 UTC, OleksiiZaloznyi commented on src/main/java/com/example/bookstore/dto/category/CategoryResponseDto.java
> +//package com.example.bookstore.dto.category;
forgot to delete this

2024-01-25 14:32 UTC, OleksiiZaloznyi commented on src/main/java/com/example/bookstore/dto/category/CategoryRequestDto.java
> +//package com.example.bookstore.dto.category;
forgot to delete this